apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql-server
  template:
    metadata:
      labels:
        app: graphql-server
    spec:
      containers:
        - name: graphql-container
          image: devdk3515/grph_srv:latest
          ports:
            - containerPort: 4000
