apiVersion: v1
kind: Service
metadata:
  name: graphql-server-service
spec:
  type: LoadBalancer
  selector:
    app: graphql-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
